#!/bin/sh

NAME="$1"
shift

help()
{
  echo "Usage:"
  echo "    <name> c|connect <host> # Start jumpbox and connect to VPN"
  echo "    <name> t|tunnel <remote_ip>:<remote_port> local_port # Create tunnel to REMOTE_IP:REMOTE_PORT on LOCAL_PORT"
  echo "    <name> dns <domain> # Lookup domain on VPN"
}


connect()
{
  docker run --rm -it \
  --name ocjb-$NAME \
  --privileged \
  -p 2222:22 \
  -e SSH_AUTH_KEY="$(cat ~/.ssh/id_rsa.pub)" \
  ocjb \
  openconnect --no-dtls $1
}

dns()
{
    docker exec -it ocjb-$NAME dig $1
}

tunnel()
{
  remote=$1
  port=$2
  if (echo "$port" | grep -Evq '^[0-9]{4,5}$'); then
    echo "Invalid port: $port"
    help
    exit 1
  fi

  if (echo "$remote" | grep -Evq '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:[0-9]{2,5}$'); then
    echo "Invalid remote spec: $remote"
    help
    exit 1
  fi

  echo "Mapping $remote to $port"
  ssh -o "UserKnownHostsFile /dev/null" -o "StrictHostKeyChecking no" -nNT -L "$port:$remote" root@localhost -p 2222
}

case $1 in
    c | connect ) shift; connect $@ ;;
    t | tunnel)  shift; tunnel $@ ;;
    nslookup | lookup | dig | dns ) shift; dns $@ ;;
    help | -h | --help ) help ;;
    *) help ; exit 1 ;;
esac
